import { TUserRequestData } from '../../utils/types';

const requestdata: TUserRequestData[] = [
  {
    id: 1,
    date: '12.04.2022',
    autoservice: 'Колесо фортуны',
    carmodel: 'lamba',
    problem:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi magnam atque, vitae commodi quia incidunt cum maxime nihil! Veniam odit possimus quisquam placeat. Nobis suscipit praesentium autem, esse quae maxime.',
    status: 'Готов',
  },
  {
    id: 2,
    date: '12.04.2022',
    autoservice: 'adfasdf фортуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 3,
    date: '12.04.2022',
    autoservice: 'Кurtyuryt фортуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 4,
    date: '12.08.2022',
    autoservice: 'vbsrtgо фортуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 5,
    date: '12.08.2022',
    autoservice: 'Коargdfbgуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 6,
    date: '12.08.2022',
    autoservice: 'gdrgsdf',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 7,
    date: '12.08.2022',
    autoservice: 'a3ardhsgf',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 8,
    date: '12.08.2022',
    autoservice: 'aefrr7',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 9,
    date: '12.08.2022',
    autoservice: 'afjryu',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 10,
    date: '29.12.2022',
    autoservice: 'age6yhd',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 11,
    date: '29.12.2022',
    autoservice: 'arfsdrgyj',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 12,
    date: '29.12.2022',
    autoservice: 'afsrdg',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 13,
    date: '29.12.2022',
    autoservice: 'afgsg',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 14,
    date: '29.12.2022',
    autoservice: 'Колесо фортуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 15,
    date: '29.12.2022',
    autoservice: 'Колесо фортуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 16,
    date: '01.02.2023',
    autoservice: 'Колесо фортуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 17,
    date: '01.02.2023',
    autoservice: 'Колесо фортуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 18,
    date: '01.02.2023',
    autoservice: 'Колесо фортуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 19,
    date: '01.02.2023',
    autoservice: 'Колесо фортуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
  {
    id: 20,
    date: '01.02.2023',
    autoservice: 'Колесо фортуны',
    carmodel: 'lamba',
    problem: 'Поломка двигателся',
    status: 'В процессе',
  },
];

export default requestdata;
